description: A package based on the directories crate from Rust, made for Dart.

dependencies:
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

name: triangle

platforms:
  linux:
  macos:
  windows:

repository: https://github.com/hammerhai/triangle

version: 1.0.0
